title: Scary Spot the Difference
hero_image: images/banner.png
description: Make a scary spot the difference game in Python
original_url: https://raspberrypi.org/learning/scary-spot-the-difference
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3.1.0
last_tested: 2018-03-22
steps: 
- title: Introduction
- title: Getting started
- title: Setting up your prank
- title: Displaying an image
- title: Switching images
- title: Making it random
- title: Adding some sound
- title: "Challenge: Taking it further"
  challenge: true
- title: What next?